version: 2
jobs:
  build:
    docker:
      # The first image listed is where the run commands are executed
      - image: driveclutch/circleci-generic:latest
    # Copy the source from github to the working_directory, all commands
    # execute relative to here.
    working_directory: /src
    steps:
      # Checkout the repo and load it into the working_directory
      - checkout
      - setup_remote_docker
      # Deployment: Making the container images, maybe pushing to dev in the
      # future
      - run: /tools/docker.sh

workflows:
  version: 2
  branch:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              ignore: /^.*/
  tag:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/